sudo: false,
language: node_js

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x
  - SENECA_VER=@3.x.x

node_js:
  - '6'
  - '4'

before_script:
  - npm uninstall seneca
  - npm install seneca$SENECA_VER

cache:
  directories:
    - node_modules

after_script:
  - npm run coveralls
