sudo: false,
language: node_js

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x

node_js:
  - '6'
  - '5'
  - '4'

before_script:
  - if [[ $TRAVIS_NODE_VERSION == "6" ]]; then export LAB_FLAGS="--leaks"; else export LAB_FLAGS=""; fi
  - npm uninstall seneca
  - npm install seneca$SENECA_VER
  - echo FLAGS:$LAB_FLAGS

cache:
  directories:
    - node_modules

after_script:
  - npm run coveralls
